image: gradle:8.7-jdk17

stages:
  - test
  - build
  - docker

# using general tags for shared runners
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  DOCKER_HOST: tcp://docker:2375

cache:
  paths:
    - .gradle/

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle

test:
  stage: test
  script:
    - gradle test
  tags:
    - docker

build:
  stage: build
  script:
    - gradle clean build
  artifacts:
    paths:
      - build/libs/*.jar
      - build/version/version.txt
  tags:
    - docker

docker:
  stage: docker
  image: docker:20.10.7
  services:
    - name: docker:dind
      command: ["--tls=false", "--host=tcp://0.0.0.0:2375"]
  script:
    - env
    - export ARTIFACT_VERSION=$(cat build/version/version.txt)
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY
    - docker build --build-arg VERSION=$ARTIFACT_VERSION -t $DOCKER_IMAGE:$ARTIFACT_VERSION .
    - docker push $DOCKER_IMAGE:$ARTIFACT_VERSION
  only:
    - develop
  tags:
    - docker
