image: gradle:8.7-jdk17

stages:
  - test
  - build
  - docker

# using general tags for shared runners
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  DOCKER_HOST: tcp://docker:2375
  CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE
  CI_COMMIT_TAG: $CI_COMMIT_TAG
  CI_REGISTRY_USER: $CI_REGISTRY_USER
  CI_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
  CI_REGISTRY: $CI_REGISTRY

cache:
  paths:
    - .gradle/

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle

test:
  stage: test
  script:
    - gradle test
  tags:
    - docker

build:
  stage: build
  script:
    - gradle clean build
  artifacts:
    paths:
      - build/libs/*.jar
  tags:
    - docker

docker:
  stage: docker
  image: docker:20.10.7
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD --password-stdin $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - develop
  tags:
    - docker
