trigger:
  branches:
    include:
      - main

pool:
  name: petclinic-agent-pool

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

steps:
#   - task: JavaToolInstaller@0
#     inputs:
#       versionSpec: '17'
#       jdkArchitectureOption: 'x64'
#       jdkSourceOption: 'PreInstalled'


#   - script: |
#       echo "JAVA_HOME: $JAVA_HOME"
#       java -version
#     displayName: 'Verify Java Installation'

#---------------------------------------------------------------------
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
    displayName: 'Use preinstalled Java'

  - script: |
      echo "##vso[task.setvariable variable=JAVA_HOME]/usr/lib/jvm/java-17-openjdk-amd64"
    displayName: 'Set JAVA_HOME'
#----------------------------------------------------------------------
  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'clean build'
      options: '--no-daemon'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'build/libs'
      artifactName: 'petclinic-jar'
