trigger:
  branches:
    include:
      - main

pool:
  name: petclinic-agent-pool
  demands:
    - agent.version -gt 4.0.0

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitecture: 'x64'
      jdkSourceOption: 'PreInstalled'

  - script: |
      echo "JAVA_HOME: $JAVA_HOME"
      java -version
    displayName: 'Verify Java Installation'

  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'clean build'
      options: '--no-daemon'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'build/libs'
      artifactName: 'petclinic-jar'
